# Parameters

# trajectory to follow
waypoints_file: ./results/recorded_trajectory_3.txt

# Sampling Time
sampling_time: 0.05
 
model:
  L: 2.7

# Controller related parameters
control:

  strategy: pure-pursuit # pid/pure-pursuit/stanley/mpc
 
  # Actuation 
  max_throttle: 0.85
  max_brake : 0.3
  max_steering : 0.8
   
  # Longitudinal controller  
  longitudinal:

    # TODO Tune these parameters
    pid:
      K_P: 35.0 #10.4
      K_D: 7.0 #20.8
      K_I: 7.0 #10.7

  # Lateral controller
  lateral:     

    # TODO Tune these parameters
    pid:
      K_P: 0.2 #1.5
      K_D: 0.1 #2.8
      K_I: 0.1 #0.7
    
    # TODO Tune these parameters
    pure-pursuit:
     ld: 15.0
     K_pp: 2.0
    
    # TODO Tune this parameter
    stanley:
      K_cte: 0

planning:
  max_len: 20.0
  min_distance: 2.0
  hop_resolution: 1.0
  speed_limit: 50.0

  lookahead_time: 2.0
  local_resolution: 0.5
